name: Build and deploy Node.js app to Azure Web App - yassercloud

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Or 22.x if required

      - name: npm install, build, and test
        working-directory: Rent-a-Spot/Backend
        run: |
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: Rent-a-Spot/Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_86079328FA66488E80240B2CF1FDA907 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_71B58F93BB8E424C9BB53DE48B3400F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C68B337956E458B93B4ED574894BD94 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'yassercloud'
          slot-name: 'Production'
          package: .
